services:
  - type: web
    name: po-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: po_api
      - key: PORT
        value: 3000
      - key: GATEWAY_SHARED_SECRET
        sync: false
